version: '3'
services: 
  node-app:
    container_name: e-commerce
    build: .
    volumes:
      - ./:/app:ro
    ports:
      - "8000:8000"
    env_file:
      - ./confiqq.env

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-db-e-commerces:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: osossama
      MONGO_INITDB_ROOT_PASSWORD: C1800109CD
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: osossama
      ME_CONFIG_MONGODB_ADMINPASSWORD: C1800109CD
      ME_CONFIG_MONGODB_URL: mongodb://osossama:C1800109CD@mongo:27017/
      ME_CONFIG_BASICAUTH: false 

volumes:
 mongo-db-e-commerces:
